import { useEffect, useMemo, useState } from "react";
import { useCollection } from "@cloudscape-design/collection-hooks";
import Alert from "@cloudscape-design/components/alert";
import AppLayout from "@cloudscape-design/components/app-layout";
import BarChart from "@cloudscape-design/components/bar-chart";
import Box from "@cloudscape-design/components/box";
import ColumnLayout from "@cloudscape-design/components/column-layout";
import Container from "@cloudscape-design/components/container";
import ContentLayout from "@cloudscape-design/components/content-layout";
import ExpandableSection from "@cloudscape-design/components/expandable-section";
import Header from "@cloudscape-design/components/header";
import KeyValuePairs from "@cloudscape-design/components/key-value-pairs";
import Link from "@cloudscape-design/components/link";
import List from "@cloudscape-design/components/list";
import Pagination from "@cloudscape-design/components/pagination";
import ProgressBar from "@cloudscape-design/components/progress-bar";
import SegmentedControl from "@cloudscape-design/components/segmented-control";
import SideNavigation from "@cloudscape-design/components/side-navigation";
import SpaceBetween from "@cloudscape-design/components/space-between";
import StatusIndicator from "@cloudscape-design/components/status-indicator";
import Steps from "@cloudscape-design/components/steps";
import Table from "@cloudscape-design/components/table";
import TextFilter from "@cloudscape-design/components/text-filter";
import TopNavigation from "@cloudscape-design/components/top-navigation";
import { applyMode, Mode } from "@cloudscape-design/global-styles";

// Result statuses map to Cloudscape status indicator types. Incomplete means
// the criterion was verified and not met; error means it could not be assessed.
const CHECK_STATUS = {
  complete: { type: "success", label: "Complete" },
  incomplete: { type: "error", label: "Incomplete" },
  error: { type: "warning", label: "Error" },
};

const CRITERION_STATUS = {
  complete: { type: "success", label: "Complete" },
  incomplete: { type: "error", label: "Not complete" },
  error: { type: "warning", label: "Error" },
  not_assessed: { type: "stopped", label: "Not assessed" },
};

const LEVEL_STATE = {
  achieved: { type: "success", label: "Achieved" },
  current: { type: "success", label: "Current level" },
  next: { type: "in-progress", label: "Next target" },
  later: { type: "pending", label: "Later level" },
};

const SUN_ICON = (
  <svg viewBox="0 0 16 16" focusable="false" aria-hidden="true">
    <circle cx="8" cy="8" r="3" fill="none" stroke="currentColor" strokeWidth="2" />
    <path
      d="M8 1v1.5M8 13.5V15M1 8h1.5M13.5 8H15M3.05 3.05l1.06 1.06M11.89 11.89l1.06 1.06M3.05 12.95l1.06-1.06M11.89 4.11l1.06-1.06"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
    />
  </svg>
);

const MOON_ICON = (
  <svg viewBox="0 0 16 16" focusable="false" aria-hidden="true">
    <path
      d="M13.5 10.2A6 6 0 0 1 5.8 2.5 6 6 0 1 0 13.5 10.2Z"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinejoin="round"
    />
  </svg>
);

export const REPOSITORY = {
  name: "aws-samples/sample-wa-foundations-assessment",
  url: "https://github.com/aws-samples/sample-wa-foundations-assessment",
};

function ReportFooter() {
  return (
    <footer>
      <Box textAlign="center" color="text-body-secondary" fontSize="body-s" padding={{ vertical: "l" }}>
        Generated by the Well-Architected Foundations Assessment tool ·{" "}
        <Link external href={REPOSITORY.url} fontSize="body-s">
          {REPOSITORY.name}
        </Link>
      </Box>
    </footer>
  );
}

function safeHref(url) {
  // Remediation links come from repository code, but never render a
  // non-HTTP(S) URL such as javascript: as a link target.
  return typeof url === "string" && /^https?:\/\//i.test(url) ? url : undefined;
}

function Status({ map, status, wrapText }) {
  const entry = map[status] || { type: "info", label: status };
  return (
    <StatusIndicator type={entry.type} wrapText={wrapText}>
      {entry.label}
    </StatusIndicator>
  );
}

function Section({ id, children }) {
  return (
    <section id={id} className="report-section" style={{ scrollMarginTop: 72 }}>
      {children}
    </section>
  );
}

function sectionsFor(data) {
  const sections = [
    { id: "overview", text: "Assessment Overview" },
    { id: "maturity", text: "Maturity Progress" },
    { id: "capabilities", text: "Capability Coverage" },
    { id: "checks", text: "Check Results" },
  ];
  if (data.delegated_admins.length) {
    sections.push({ id: "delegated-admins", text: "Delegated Administrators" });
  }
  if (data.maturity.scoring_model) {
    sections.push({ id: "methodology", text: "Maturity Methodology" });
  }
  return sections;
}

function useActiveSection(sections) {
  const [active, setActive] = useState(sections[0].id);
  useEffect(() => {
    if (typeof IntersectionObserver === "undefined") {
      return undefined;
    }
    const observer = new IntersectionObserver(
      (entries) => {
        const visible = entries
          .filter((entry) => entry.isIntersecting)
          .sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top);
        if (visible.length) {
          setActive(visible[0].target.id);
        }
      },
      { rootMargin: "-10% 0px -75% 0px" },
    );
    sections.forEach(({ id }) => {
      const element = document.getElementById(id);
      if (element) {
        observer.observe(element);
      }
    });
    return () => observer.disconnect();
  }, [sections]);
  return [active, setActive];
}

function Overview({ data }) {
  const { maturity, summary, account_info: accountInfo } = data;
  const isLimited =
    Object.keys(accountInfo).length > 0 && !accountInfo.is_management_account;
  const accountType = accountInfo.account_type || "N/A";
  return (
    <Container header={<Header variant="h2">Assessment Overview</Header>}>
      <SpaceBetween size="l">
        <ColumnLayout columns={2} variant="text-grid">
          <SpaceBetween size="xs">
            <Box variant="awsui-key-label">Maturity level</Box>
            <Box variant="awsui-value-large">L{maturity.level}</Box>
            <Box variant="h3">{maturity.name}</Box>
            <Box color="text-body-secondary">{maturity.description}</Box>
          </SpaceBetween>
          <KeyValuePairs
            columns={2}
            items={[
              { label: "Account", value: accountInfo.account_id || "N/A" },
              { label: "Account type", value: accountType },
              { label: "Organization", value: accountInfo.organization_id || "N/A" },
              {
                label: "Management account",
                value: accountInfo.management_account_id || "N/A",
              },
            ]}
          />
        </ColumnLayout>
        <ColumnLayout columns={5} variant="text-grid" minColumnWidth={120}>
          <Counter label="Total Checks" value={summary.total} />
          <Counter label="Complete" value={summary.complete} status="complete" />
          <Counter label="Incomplete" value={summary.incomplete} status="incomplete" />
          <Counter label="Errors" value={summary.errors} status="error" />
          <Counter label="Completion" value={`${summary.pct}%`} />
        </ColumnLayout>
        {isLimited && (
          <Alert type="warning" header="Limited assessment">
            This maturity level is provisional for the {accountType} account.
            Organization-wide checks were not run. Run the Well-Architected
            Foundations Assessment tool from the management account for a
            complete maturity assessment.
          </Alert>
        )}
      </SpaceBetween>
    </Container>
  );
}

function Counter({ label, value, status }) {
  return (
    <div>
      <Box variant="awsui-key-label">
        {status ? (
          <StatusIndicator type={CHECK_STATUS[status].type}>{label}</StatusIndicator>
        ) : (
          label
        )}
      </Box>
      <Box variant="awsui-value-large">{value}</Box>
    </div>
  );
}

// Five horizontal steps do not fit a phone-width viewport.
const NARROW_QUERY = "(max-width: 688px)";

function useIsNarrow() {
  const query = useMemo(
    () =>
      typeof window !== "undefined" && window.matchMedia
        ? window.matchMedia(NARROW_QUERY)
        : null,
    [],
  );
  const [isNarrow, setIsNarrow] = useState(query ? query.matches : false);
  useEffect(() => {
    if (!query) {
      return undefined;
    }
    const onChange = (event) => setIsNarrow(event.matches);
    query.addEventListener("change", onChange);
    return () => query.removeEventListener("change", onChange);
  }, [query]);
  return isNarrow;
}

function MaturityProgress({ maturity }) {
  const levels = maturity.scoring_model ? maturity.scoring_model.levels : [];
  const isNarrow = useIsNarrow();
  return (
    <Container header={<Header variant="h2">Maturity Progress</Header>}>
      <SpaceBetween size="l">
        {levels.length > 0 && (
          <Steps
            orientation={isNarrow ? "vertical" : "horizontal"}
            ariaLabel="Maturity level progression"
            steps={levels.map((level) => {
              const state = LEVEL_STATE[level.state] || LEVEL_STATE.later;
              return {
                status: state.type,
                statusIconAriaLabel: state.label,
                header: `Level ${level.level} — ${level.name}`,
                details: (
                  <SpaceBetween size="xxs">
                    <Box fontWeight="bold">{state.label}</Box>
                    <Box color="text-body-secondary">
                      {level.criteria_count
                        ? `${level.complete_count}/${level.criteria_count} criteria`
                        : "Baseline"}
                    </Box>
                  </SpaceBetween>
                ),
              };
            })}
          />
        )}
        {maturity.next_level ? (
          <SpaceBetween size="m">
            <ProgressBar
              value={maturity.next_level_progress}
              label={`Progress toward Level ${maturity.next_level}`}
            />
            {maturity.next_level_checks_needed &&
              maturity.next_level_checks_needed.length > 0 && (
                <SpaceBetween size="xs">
                  <Header variant="h3">Next steps (highest impact first)</Header>
                  <List
                    tagOverride="ol"
                    ariaLabel="Next steps"
                    items={maturity.next_level_checks_needed.slice(0, 5)}
                    renderItem={(name) => ({ id: name, content: name })}
                  />
                </SpaceBetween>
              )}
          </SpaceBetween>
        ) : (
          <Alert type="success">All Phase 1 criteria met.</Alert>
        )}
      </SpaceBetween>
    </Container>
  );
}

function CapabilityCoverage({ axes }) {
  const gaps = axes.filter((axis) => axis.check_count === 0);
  return (
    <Container
      header={
        <Header
          variant="h2"
          description="Percentage of mapped checks that are complete for each WA Foundations capability."
        >
          Capability Coverage (WA Foundations)
        </Header>
      }
    >
      <SpaceBetween size="m">
        <BarChart
          ariaLabel="WA Foundations capability coverage"
          horizontalBars
          hideFilter
          hideLegend
          height={320}
          xScaleType="categorical"
          yDomain={[0, 100]}
          xTitle="Capability"
          yTitle="Coverage (%)"
          series={[
            {
              title: "Coverage",
              type: "bar",
              data: axes.map((axis) => ({ x: axis.name, y: axis.score })),
              valueFormatter: (value) => `${value}%`,
            },
          ]}
        />
        {gaps.length > 0 && (
          <Box color="text-body-secondary" fontSize="body-s">
            {gaps.map((axis) => axis.name).join(", ")}: no Phase 1 checks are
            mapped to this capability yet, so it reports 0% coverage.
          </Box>
        )}
      </SpaceBetween>
    </Container>
  );
}

const STATUS_FILTERS = [
  { id: "all", text: "All" },
  { id: "complete", text: "Complete" },
  { id: "incomplete", text: "Incomplete" },
  { id: "error", text: "Errors" },
];

function CheckResults({ checks, summary }) {
  const [statusFilter, setStatusFilter] = useState("all");
  const counts = {
    all: summary.total,
    complete: summary.complete,
    incomplete: summary.incomplete,
    error: summary.errors,
  };
  const statusItems = useMemo(
    () =>
      statusFilter === "all"
        ? checks
        : checks.filter((check) => check.status === statusFilter),
    [checks, statusFilter],
  );
  const { items, collectionProps, filterProps, filteredItemsCount, paginationProps } =
    useCollection(statusItems, {
      filtering: {
        fields: ["check", "description", "status", "error"],
        empty: <Box textAlign="center">No checks with this status.</Box>,
        noMatch: <Box textAlign="center">No checks match the filter.</Box>,
      },
      sorting: {},
      pagination: { pageSize: 50 },
    });

  return (
    <SpaceBetween size="l">
      <Container
        header={
          <Header
            variant="h2"
            description="Only Complete results contribute to completion and capability scores. Incomplete and Error results do not satisfy maturity criteria. An Error does not necessarily mean the configuration is incorrect."
          >
            Check Results
          </Header>
        }
      >
        <div aria-label="Check result status definitions" role="group">
          <ColumnLayout columns={3} borders="vertical">
            <SpaceBetween size="xxs">
              <Status map={CHECK_STATUS} status="complete" />
              <Box>Verified and meets the criterion.</Box>
            </SpaceBetween>
            <SpaceBetween size="xxs">
              <Status map={CHECK_STATUS} status="incomplete" />
              <Box>Verified but does not meet the criterion.</Box>
            </SpaceBetween>
            <SpaceBetween size="xxs">
              <Status map={CHECK_STATUS} status="error" />
              <Box>
                Could not be reliably assessed, usually because of permissions
                or an AWS API failure.
              </Box>
            </SpaceBetween>
          </ColumnLayout>
        </div>
      </Container>
      <Table
        {...collectionProps}
        variant="container"
        ariaLabels={{ tableLabel: "Check results" }}
        header={
          <Header
            variant="h3"
            counter={`(${checks.length})`}
            actions={
              <SegmentedControl
                label="Filter by status"
                selectedId={statusFilter}
                onChange={({ detail }) => setStatusFilter(detail.selectedId)}
                options={STATUS_FILTERS.map((option) => ({
                  id: option.id,
                  text: `${option.text} (${counts[option.id]})`,
                }))}
              />
            }
          >
            Checks
          </Header>
        }
        filter={
          <TextFilter
            {...filterProps}
            filteringPlaceholder="Find checks"
            filteringAriaLabel="Filter checks"
            countText={`${filteredItemsCount} ${filteredItemsCount === 1 ? "match" : "matches"}`}
          />
        }
        pagination={<Pagination {...paginationProps} />}
        wrapLines
        items={items}
        columnDefinitions={[
          {
            // Fixed widths on the other columns leave the remaining space to
            // the wrapping Check column, so status labels stay on one line
            // even with the report sections navigation open.
            id: "check",
            header: "Check",
            sortingField: "check",
            isRowHeader: true,
            cell: (check) => (
              <SpaceBetween size="xxxs">
                <Box fontWeight="bold">{check.check}</Box>
                <Box color="text-body-secondary" fontSize="body-s">
                  {check.description}
                </Box>
                {check.error && (
                  <Box color="text-status-error" fontSize="body-s">
                    {check.error}
                  </Box>
                )}
              </SpaceBetween>
            ),
          },
          {
            id: "status",
            width: 150,
            header: "Status",
            sortingField: "status",
            // Long AWS error text in the Check column must not squeeze the
            // status label into a mid-word wrap.
            cell: (check) => (
              <Status map={CHECK_STATUS} status={check.status} wrapText={false} />
            ),
          },
          {
            id: "required",
            width: 120,
            header: "Required",
            sortingField: "required",
            cell: (check) => (check.required ? "Yes" : "No"),
          },
          {
            id: "loe",
            header: "LoE",
            width: 80,
            sortingField: "loe",
            cell: (check) => check.loe,
          },
          {
            id: "remediation",
            width: 130,
            header: "Remediation",
            cell: (check) =>
              safeHref(check.remediationLink) ? (
                <Link
                  external
                  href={safeHref(check.remediationLink)}
                  ariaLabel={`Remediation guidance for ${check.check}`}
                >
                  Fix
                </Link>
              ) : (
                "—"
              ),
          },
        ]}
      />
    </SpaceBetween>
  );
}

function DelegatedAdmins({ admins }) {
  return (
    <Table
      variant="container"
      ariaLabels={{ tableLabel: "Delegated administrators" }}
      header={
        <Header variant="h2" counter={`(${admins.length})`}>
          Delegated Administrators
        </Header>
      }
      items={admins}
      wrapLines
      columnDefinitions={[
        {
          id: "accountId",
          header: "Account ID",
          isRowHeader: true,
          cell: (admin) => admin.accountId,
        },
        { id: "accountName", header: "Account Name", cell: (admin) => admin.accountName },
        {
          id: "services",
          header: "Delegated Services",
          cell: (admin) => (admin.services || []).join(", "),
        },
      ]}
    />
  );
}

function Methodology({ model }) {
  return (
    <Container header={<Header variant="h2">Maturity Methodology</Header>}>
      <SpaceBetween size="l">
        <Box>
          {model.rule} {model.weight_note}
        </Box>
        {model.levels.map((level) => (
          <ExpandableSection
            key={level.level}
            variant="container"
            defaultExpanded
            headerText={`Level ${level.level} — ${level.name}`}
            headerCounter={
              level.criteria_count
                ? `(${level.complete_count}/${level.criteria_count} complete)`
                : "(Baseline level)"
            }
            headerDescription={level.description}
          >
            {level.criteria && level.criteria.length > 0 ? (
              <List
                ariaLabel={`Level ${level.level} criteria`}
                items={level.criteria}
                renderItem={(criterion) => ({
                  id: criterion.name,
                  content: criterion.name,
                  secondaryContent: criterion.detail,
                  actions: <Status map={CRITERION_STATUS} status={criterion.status} />,
                })}
              />
            ) : (
              <Box color="text-body-secondary">
                No additional criteria for this level.
              </Box>
            )}
          </ExpandableSection>
        ))}
      </SpaceBetween>
    </Container>
  );
}

export function initialMode() {
  return typeof window !== "undefined" &&
    window.matchMedia &&
    window.matchMedia("(prefers-color-scheme: dark)").matches
    ? Mode.Dark
    : Mode.Light;
}

export default function App({ data }) {
  const sections = useMemo(() => sectionsFor(data), [data]);
  const [activeSection, setActiveSection] = useActiveSection(sections);
  const [mode, setMode] = useState(initialMode);
  const [navigationOpen, setNavigationOpen] = useState(true);

  useEffect(() => {
    applyMode(mode);
  }, [mode]);

  const isDark = mode === Mode.Dark;
  const accountInfo = data.account_info;

  return (
    <>
      <div id="wafa-top-nav" style={{ position: "sticky", top: 0, zIndex: 1002 }}>
        <TopNavigation
          identity={{ href: "#overview", title: "Well-Architected Foundations Assessment" }}
          utilities={[
            {
              type: "button",
              iconSvg: isDark ? SUN_ICON : MOON_ICON,
              ariaLabel: isDark ? "Switch to light mode" : "Switch to dark mode",
              title: isDark ? "Light mode" : "Dark mode",
              onClick: () => setMode(isDark ? Mode.Light : Mode.Dark),
            },
          ]}
        />
      </div>
      <AppLayout
        headerSelector="#wafa-top-nav"
        toolsHide
        navigationOpen={navigationOpen}
        onNavigationChange={({ detail }) => setNavigationOpen(detail.open)}
        ariaLabels={{
          navigation: "Report sections",
          navigationToggle: "Open report sections",
          navigationClose: "Close report sections",
        }}
        navigation={
          <SideNavigation
            header={{ text: "Report sections", href: "#overview" }}
            activeHref={`#${activeSection}`}
            onFollow={(event) => {
              event.preventDefault();
              const id = event.detail.href.slice(1);
              setActiveSection(id);
              const element = document.getElementById(id);
              if (element) {
                element.scrollIntoView({ behavior: "smooth", block: "start" });
              }
            }}
            items={sections.map((section) => ({
              type: "link",
              text: section.text,
              href: `#${section.id}`,
            }))}
          />
        }
        content={
          <ContentLayout
            header={
              <Header
                variant="h1"
                description={`Account: ${accountInfo.account_id || "N/A"} (${accountInfo.account_type || "N/A"})`}
              >
                Well-Architected Foundations Assessment Report
              </Header>
            }
          >
            <SpaceBetween size="l">
              <Section id="overview">
                <Overview data={data} />
              </Section>
              <Section id="maturity">
                <MaturityProgress maturity={data.maturity} />
              </Section>
              <Section id="capabilities">
                <CapabilityCoverage axes={data.axis_scores} />
              </Section>
              <Section id="checks">
                <CheckResults checks={data.checks} summary={data.summary} />
              </Section>
              {data.delegated_admins.length > 0 && (
                <Section id="delegated-admins">
                  <DelegatedAdmins admins={data.delegated_admins} />
                </Section>
              )}
              {data.maturity.scoring_model && (
                <Section id="methodology">
                  <Methodology model={data.maturity.scoring_model} />
                </Section>
              )}
              <ReportFooter />
            </SpaceBetween>
          </ContentLayout>
        }
      />
    </>
  );
}
