"""HTML Report Generation (FR-10.1).

Generates a self-contained HTML report built from Cloudscape Design System
components. The React UI is compiled from ``report-ui/`` into the static
bundle under ``assets/`` and inlined into every report together with the
assessment data, so the report renders without any network access.

The report contains:
- Maturity level score and progress
- Capability coverage bar chart over the 7 WA Foundations capability axes
- Assessment overview
- Check results table with filtering
- Delegated administrators table
- Light/dark mode toggle
"""

from functools import cache
from pathlib import Path

from jinja2 import BaseLoader, select_autoescape
from jinja2.sandbox import SandboxedEnvironment

ASSETS_DIR = Path(__file__).parent / "assets"

# FR-10.1: Capability chart axis mapping — check names to capability axes
CAPABILITY_AXES = {
    "Multi-Account Environment": [
        "AWS Organization exists",
        "Management account identified",
        "Minimum 4 accounts",
        "Log Archive account exists",
        "Audit account exists",
        "Service Control Policies enabled",
        "Tag Policies enabled",
        "Backup Policies enabled",
        "Resource Control Policies enabled",
        "Security OU exists",
        "Workloads OU exists",
        "Infrastructure OU exists",
    ],
    "Identity & Access Management": [
        "Service Control Policies enabled",
        "Resource Control Policies enabled",
        "IAM Access Analyzer organization service enabled",
        "IAM Identity Center organization service enabled",
        "IAM Identity Center configured",
        "No IAM users in account",
    ],
    "Central Observability": [
        "CloudTrail organization service enabled",
        "CloudTrail trail exists",
        "CloudTrail organization trail",
    ],
    "Resource & Inventory Management": [
        "Tag Policies enabled",
        "Backup Policies enabled",
        "AWS Config organization service enabled",
        "AWS Backup organization service enabled",
    ],
    "Security & Compliance": [
        "CloudTrail organization service enabled",
        "GuardDuty organization service enabled",
        "Security Hub organization service enabled",
        "CloudTrail trail exists",
        "CloudTrail organization trail",
        "AWS Config recorder active",
        "AWS Config delivery channel active",
        "Log Archive account exists",
    ],
    "Cloud Financial Management": [
        "Tag Policies enabled",
        "Cost Optimization Hub organization service enabled",
        "Cost and Usage Report configured",
    ],
    "Networking & Connectivity": [],
}


def _calculate_axis_scores(checks):
    """Calculate percentage score per capability axis."""
    scores = {}
    for axis_name, check_names in CAPABILITY_AXES.items():
        complete = sum(
            1
            for name in check_names
            if any(
                c.get("check") == name and c.get("status") == "complete" for c in checks
            )
        )
        scores[axis_name] = (
            round((complete / len(check_names)) * 100) if check_names else 0
        )
    return scores


@cache
def _load_asset(name):
    """Return a prebuilt report UI asset.

    The assets are generated by ``npm run build`` in ``report-ui/``. The build
    escapes closing ``</script`` and ``</style`` sequences, so they are trusted
    repository code that the template inlines with ``safe``.
    """
    return (ASSETS_DIR / name).read_text(encoding="utf-8")


def _build_report_data(checks, maturity, delegated_admins, account_info):
    """Assemble the JSON payload rendered by the Cloudscape report UI."""
    axis_scores = _calculate_axis_scores(checks)
    total = len(checks)
    complete = sum(1 for c in checks if c["status"] == "complete")
    incomplete = sum(1 for c in checks if c["status"] == "incomplete")
    errors = sum(1 for c in checks if c["status"] == "error")
    return {
        "checks": checks,
        "maturity": maturity,
        "delegated_admins": delegated_admins,
        "account_info": account_info,
        "axis_scores": [
            {
                "name": name,
                "score": score,
                "check_count": len(CAPABILITY_AXES[name]),
            }
            for name, score in axis_scores.items()
        ],
        "summary": {
            "total": total,
            "complete": complete,
            "incomplete": incomplete,
            "errors": errors,
            "pct": round(complete / total * 100) if total > 0 else 0,
        },
    }


def generate_html(checks, maturity, delegated_admins=None, account_info=None):
    """Generate the interactive HTML report.

    Args:
        checks: list of check result dicts
        maturity: maturity level result dict
        delegated_admins: list of delegated admin dicts (optional)
        account_info: account info dict (optional)

    Returns:
        str: Complete HTML document as string
    """
    if delegated_admins is None:
        delegated_admins = []
    if account_info is None:
        account_info = {}

    # The report is a standalone HTML document, so use a sandboxed environment
    # with autoescaping instead of relying on a web framework's renderer.
    env = SandboxedEnvironment(
        loader=BaseLoader(),
        autoescape=select_autoescape(default_for_string=True, default=True),
    )
    # Match the raw JSON export: non-JSON AWS values such as datetimes are
    # rendered as strings instead of failing the report.
    env.policies["json.dumps_kwargs"] = {"sort_keys": True, "default": str}
    template = env.from_string(HTML_TEMPLATE)
    rendered = template.render(
        # tojson escapes <, >, &, and ' as Unicode escapes, so AWS-provided
        # text cannot break out of the JSON data element.
        report_data=_build_report_data(
            checks, maturity, delegated_admins, account_info
        ),
        report_css=_load_asset("report-ui.css"),
        report_js=_load_asset("report-ui.js"),
    )
    return "\n".join(line.rstrip() for line in rendered.splitlines()) + "\n"


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>WA-Foundations Report</title>
<style>
{{ report_css | safe }}
</style>
</head>
<body>
<noscript>
    <h1>Well-Architected Foundations Assessment Report</h1>
    <p>This report requires JavaScript. The same results are available in the
    CSV and JSON files generated with this report.</p>
</noscript>
<div id="wafa-report-root"></div>
<script type="application/json" id="wafa-report-data">{{ report_data | tojson }}</script>
<script>
{{ report_js | safe }}
</script>
</body>
</html>"""
